# Generated by Django 5.2.1 on 2025-05-30 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20250528_2355'),
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNoteProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.studynote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Note Progress',
                'verbose_name_plural': 'Study Note Progress',
                'db_table': 'study_note_progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'study_note')},
            },
        ),
    ]
