# Generated by Django 5.2.1 on 2025-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_class_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Primary 1'), (2, 'Primary 2'), (3, 'Primary 3'), (4, 'Primary 4'), (5, 'Primary 5'), (6, 'Primary 6'), (7, 'JHS 1'), (8, 'JHS 2'), (9, 'JHS 3'), (10, 'SHS 1'), (11, 'SHS 2'), (12, 'SHS 3')], help_text="User's current class level", null=True),
        ),
    ]
