# Generated by Django 5.2.1 on 2025-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for anonymous feedback', max_length=254),
        ),
    ]
