# Generated by Django 5.2.1 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_herosection_sitestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Quality education for everyone. Start your learning journey today with our comprehensive, mobile-friendly platform designed for learners worldwide.'),
        ),
    ]
