# Generated by Django 5.2.1 on 2025-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_banner',
            field=models.ImageField(blank=True, help_text='Banner for dashboard (recommended: 1200x300px)', null=True, upload_to='site/banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Main hero banner for homepage (recommended: 1920x600px)', null=True, upload_to='site/banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_banner',
            field=models.ImageField(blank=True, help_text='Banner for login page (recommended: 800x400px)', null=True, upload_to='site/banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing (recommended: 1200x630px)', null=True, upload_to='site/social/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Site icon for mobile/PWA (recommended: 192x192px)', null=True, upload_to='site/icons/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, help_text='Site favicon (recommended: 32x32px)', null=True, upload_to='site/favicons/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Main site logo (recommended: 200x60px)', null=True, upload_to='site/logos/'),
        ),
    ]
