# Generated by Django 5.2.1 on 2025-07-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_sitesettings_dashboard_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='dashboard_banner',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='login_banner',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_icon',
        ),
    ]
