# Generated by Django 5.2.1 on 2025-05-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_display_time',
            field=models.PositiveIntegerField(default=5, help_text='Time to show explanation in seconds'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=45, help_text='Time limit per question in seconds'),
        ),
    ]
