# Generated by Django 5.2.1 on 2025-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Time taken in seconds'),
        ),
    ]
