# Generated by Django 5.2.1 on 2025-05-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_question_explanation_display_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_ids',
            field=models.JSONField(default=list, help_text='Shuffled question IDs for this quiz attempt'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seed',
            field=models.IntegerField(default=0, help_text='Random seed for consistent shuffling'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
