# Generated by Django 5.2.1 on 2025-07-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_optimize_question_indexes'),
        ('content', '0003_quiz_time_taken'),
    ]

    operations = [
    ]
