# Generated by Django 5.2.1 on 2025-05-28 23:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_quiz_attempt_number_quiz_question_ids_quiz_seed_and_more'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within passage or topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(help_text="Correct answer or answer key. For text questions, separate multiple acceptable answers with commas (e.g., 'smart, clever, intelligent, wise')"),
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The reading passage content')),
                ('passage_type', models.CharField(choices=[('story', 'Story'), ('article', 'Article'), ('poem', 'Poem'), ('dialogue', 'Dialogue'), ('informational', 'Informational Text')], default='story', max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('reading_level', models.CharField(blank=True, help_text='Grade level or difficulty', max_length=20)),
                ('estimated_reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='subjects.topic')),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
                'db_table': 'passages',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, help_text='Link to reading passage for comprehension questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.passage'),
        ),
    ]
