# Generated by Django 5.2.1 on 2025-05-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_question_order_alter_question_correct_answer_passage_and_more'),
    ]

    operations = [
    ]
