# Generated by Django 5.2.1 on 2025-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20250528_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_ids',
            field=models.JSONField(default=list, help_text='Shuffled question IDs for this exam attempt'),
        ),
        migrations.AddField(
            model_name='test',
            name='seed',
            field=models.IntegerField(default=0, help_text='Random seed for consistent shuffling'),
        ),
    ]
